### ISSUE TITLE
Cannot login though Zulip Dev Login

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#189]
After setting up the local server, and connecting to the to it, the app crashes when someone tries to login.

![logindevedited-2016-10-01-015147 1](https://cloud.githubusercontent.com/assets/14239866/19006854/7605bdc8-877f-11e6-89f2-e96d284f9f39.png)
![logindevedited-2016-10-01-015223 1](https://cloud.githubusercontent.com/assets/14239866/19006984/13e31586-8780-11e6-959e-908229284a6b.png)
![logindev-2016-10-01-015305 1](https://cloud.githubusercontent.com/assets/14239866/19006999/25a00b4e-8780-11e6-9d17-ead997ea961d.png)
![logindev-2016-10-01-015333 1](https://cloud.githubusercontent.com/assets/14239866/19007003/2de68990-8780-11e6-9a18-3ededb4fa3c5.png)

These are the error logs
```
10-01 01:54:18.521 24671-24671/com.zulip.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.zulip.android.dev, PID: 24671
                                                                       java.lang.IllegalArgumentException: @Field parameters can only be used with form encoding. (parameter #1)
                                                                           for method ZulipServices.loginDEV
                                                                           at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
                                                                           at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:711)
                                                                           at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:729)
                                                                           at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(ServiceMethod.java:501)
                                                                           at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:333)
                                                                           at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:202)
                                                                           at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
                                                                           at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
                                                                           at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                           at $Proxy1.loginDEV(Unknown Source)
                                                                           at com.zulip.android.activities.DevAuthActivity$1.onItemClick(DevAuthActivity.java:68)
                                                                           at com.zulip.android.activities.AuthEmailAdapter$AuthEmailViewHolder.onClick(AuthEmailAdapter.java:101)
                                                                           at android.view.View.performClick(View.java:5714)
                                                                           at android.widget.TextView.performClick(TextView.java:10926)
                                                                           at android.view.View$PerformClick.run(View.java:22589)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by kunall17** [comment]
@Sam1301 thanks for the PR it has been merged! Can you please close this issue now?

**Comment by Sam1301** [comment]
Sure, happy that the issue is now resolved in the app.
