### ISSUE TITLE
Error thrown on switch day/night theme

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-android#403]
On recent changes this weird error is being thrown

`02-14 13:26:47.109 15247-15270/com.zulip.android.dev A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 15270 (RenderThread)`

**Comment by saketkumar95** [comment]
@kunall17 Can you tell me how to reproduce it? it's working fine in my device.

**Comment by kunall17** [comment]
@saketkumar95 Nothing special to reproduce, it sometime occur's !

**Comment by kunall17** [comment]
Got this error today as well 
```
03-04 23:40:39.541 13352-13368/com.zulip.android.dev E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
03-04 23:40:39.541 13352-13368/com.zulip.android.dev E/EGL_emulation: tid 13368: swapBuffers(288): error 0x3003 (EGL_BAD_ALLOC)
03-04 23:40:39.541 13352-13368/com.zulip.android.dev A/OpenGLRenderer: Encountered EGL error 12291 EGL_BAD_ALLOC during rendering
03-04 23:40:39.541 13352-13368/com.zulip.android.dev A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 13368 (RenderThread)
```

**Comment by saketkumar95** [comment]
@kunall17 Will check and update you about this. This seems really naughty  bug.. :grin:

**Comment by saketkumar95** [comment]
I got this weird error at runtime. Don't know what exactly it is about. 

```Process: com.zulip.android.dev, PID: 13639
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:318)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: java.lang.RuntimeException: java.sql.SQLException: Transaction callable threw non-SQL exception
                      at com.zulip.android.models.Message.createMessages(Message.java:257)
                      at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:220)
                      at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:157)
                      at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:26)
                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
                   Caused by: java.sql.SQLException: Transaction callable threw non-SQL exception
                      at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:27)
                      at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:251)
                      at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:169)
                      at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:150)
                      at com.zulip.android.models.Message.createMessages(Message.java:238)
                      at com.zulip.android.networking.AsyncGetOldMessages.fetchMessages(AsyncGetOldMessages.java:220) 
                      at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:157) 
                      at com.zulip.android.networking.AsyncGetOldMessages.doInBackground(AsyncGetOldMessages.java:26) 
                      at android.os.AsyncTask$2.call(AsyncTask.java:304) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
                   Caused by: java.lang.RuntimeException: java.sql.SQLException: Unable to run update stmt on object com.zulip.android.models ```

**Comment by kunall17** [comment]
On the current master?

**Comment by saketkumar95** [comment]
yeah!

**Comment by saketkumar95** [comment]
I tested in the morning only. I guess https://github.com/zulip/zulip-android/pull/296 this PR  is creating some problem.

**Comment by kunall17** [comment]
Test now!

**Comment by saketkumar95** [comment]
yeah, working fine now. :)
