### ISSUE TITLE
Crash due to NullPointerException

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#457]
Stacktrace

```
Crashed: main: 0 0 0x0000000000000000
       at com.zulip.android.models.Message.getDisplayRecipient(Message.java:497)
       at com.zulip.android.activities.RecyclerMessageAdapter.addOldMessage(RecyclerMessageAdapter.java:265)
       at com.zulip.android.activities.MessageListFragment.onMessages(MessageListFragment.java:615)
       at com.zulip.android.networking.AsyncGetOldMessages.onPostExecute(AsyncGetOldMessages.java:246)
       at com.zulip.android.networking.AsyncGetOldMessages.onPostExecute(AsyncGetOldMessages.java:26)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

--

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.zulip.android.models.Person.id' on a null object reference
       at com.zulip.android.models.Message.getDisplayRecipient(Message.java:497)
       at com.zulip.android.activities.RecyclerMessageAdapter.addOldMessage(RecyclerMessageAdapter.java:265)
       at com.zulip.android.activities.MessageListFragment.onMessages(MessageListFragment.java:615)
       at com.zulip.android.networking.AsyncGetOldMessages.onPostExecute(AsyncGetOldMessages.java:246)
       at com.zulip.android.networking.AsyncGetOldMessages.onPostExecute(AsyncGetOldMessages.java:26)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Android version: 6

**Comment by nitish1211** [comment]
@zulipbot  claim-issue

**Comment by nitish1211** [comment]
@Sam1301 how did you produce the error?

**Comment by Sam1301** [comment]
@nitish1211 actually I couldn't reproduce this bug but saw it in the crashylytics log for release v1.2.1. There must be some specific state when the app crashes.

**Comment by Sam1301** [comment]
@nitish1211 here is the full stackstrace [com.zulip.android_issue_92_crash_58C094E70123000144F574BF6E44760B_7b5f9b077dcb4d13a5c40e81dd4f08f8_0_v1.txt](https://github.com/zulip/zulip-android/files/832566/com.zulip.android_issue_92_crash_58C094E70123000144F574BF6E44760B_7b5f9b077dcb4d13a5c40e81dd4f08f8_0_v1.txt) 
Also checkout the latest release version to investigate `git checkout tags/1.2.1 -b branch-name`.

**Comment by Sam1301** [comment]
@nitish1211 it might be worth to test on older releases of zulip server (https://github.com/zulip/zulip/releases)

**Comment by divs4debu** [comment]
@Sam1301  any ways we could reproduce it?

**Comment by Sam1301** [comment]
@divs4debu I couldn't reproduce this error, you'd have to look closely at the logs. 
Following the previous comments, one could also try to run zulip v1.4.x and run the app against it.
