### ISSUE TITLE
Widget: crash due to messageList null

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#458]
Stacktrace

```
Crashed: Binder_3: 0 0 0x0000000000000000
       at com.zulip.android.widget.ZulipRemoteViewsFactory.getCount(ZulipRemoteViewsFactory.java:75)
       at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getCount(RemoteViewsService.java:154)
       at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:75)
       at android.os.Binder.execTransact(Binder.java:446)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
       at com.zulip.android.widget.ZulipRemoteViewsFactory.getCount(ZulipRemoteViewsFactory.java:75)
       at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getCount(RemoteViewsService.java:154)
       at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:75)
       at android.os.Binder.execTransact(Binder.java:446)
```

Android version : 5.1.1

**Comment by zeerorg** [comment]
can you tell me how to reproduce this error?

**Comment by Sam1301** [comment]
@zeerorg so I couldn't reproduce this error but got this in crashylytics. There must be some state in which the app gets which causes this. Here's the full stacktrace([stacktrace.txt](https://github.com/zulip/zulip-android/files/843534/com.zulip.android_issue_75_crash_58C889580041000113FF2C7B506A3155_3359c2316ca1471b88163a834669ec55_0_v1.txt)) in case you want to investigate. If you still can't reproduce the error, one thing you could try is testing the app on older releases of zulip server(https://github.com/zulip/zulip/releases). For this you'll need to set your development environment (https://github.com/zulip/zulip-android#connecting-to-a-development-server).
Happy debugging :)

**Comment by divs4debu** [comment]
@Sam1301 @zeerorg 
What i think is happening is that 
in [https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/widget/ZulipRemoteViewsFactory.java](url)

` try {
            messageList = queryBuilder.query();
        } catch (SQLException e) {
            ZLog.logException(e);
        }`

This particular code is being executed i.e if querybuilder.query() returns a null object but i recently checked it , it was working fine it was returning empty list rather than null object. What i suuggest is to initialize message list in advance that will make sure the messageList instance is not null and instead of assigning the `messageList = queryBuilder.query()` we can `messageList.addAll(queryBuilder.query());`
I think this might solve any rare problem of this kind
