### ISSUE TITLE
Crash due to ArrayIndexOutOfBoundsException for RecylerMessageAdapter list items

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#459]
Stacktrace

```
Crashed: main: 0 0 0x0000000000000000
       at java.util.ArrayList.get(ArrayList.java:310)
       at com.zulip.android.activities.RecyclerMessageAdapter.getItem(RecyclerMessageAdapter.java:581)
       at com.zulip.android.activities.MessageListFragment.scrolledToLastMessage(MessageListFragment.java:791)
       at com.zulip.android.activities.ZulipActivity.onNewMessages(ZulipActivity.java:2265)
       at com.zulip.android.networking.AsyncGetEvents$6.run(AsyncGetEvents.java:401)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

--

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
       at java.util.ArrayList.get(ArrayList.java:310)
       at com.zulip.android.activities.RecyclerMessageAdapter.getItem(RecyclerMessageAdapter.java:581)
       at com.zulip.android.activities.MessageListFragment.scrolledToLastMessage(MessageListFragment.java:791)
       at com.zulip.android.activities.ZulipActivity.onNewMessages(ZulipActivity.java:2265)
       at com.zulip.android.networking.AsyncGetEvents$6.run(AsyncGetEvents.java:401)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by Jonsnow21** [comment]
@Sam1301 i would like to work on this

**Comment by brainwane** [comment]
@Sam1301 How should a user try to reproduce this error?

**Comment by timabbott** [comment]
We got this from crash reporting, so I don't think we actually know how to reproduce it.

**Comment by Sam1301** [comment]
@Jonsnow21  so I couldn't reproduce this error but got this in crashylytics. There must be some state in which the app gets which causes this. Here's the full stacktrace([stacktrace.txt](https://github.com/zulip/zulip-android/files/843539/stacktrace.txt)) in case you want to investigate. If you still can't reproduce the error, one thing you could try is testing the app on older releases of zulip server(https://github.com/zulip/zulip/releases). For this you'll need to set your development environment (https://github.com/zulip/zulip-android#connecting-to-a-development-server).
Happy debugging :)

**Comment by meghalagrawal** [comment]
Do we have any other Information about this ?

Any other instance of crashing ?

**Comment by timabbott** [comment]
I think someone will need to read the code around this stack to debug this.

**Comment by meghalagrawal** [comment]
I investigated and got 1 Thing.

The Lines Number of Methods is Changed.

And this branch has not got any Merge done after 13th.

This suggests that either this is issue on old code. I am looking into previous commits when the Line Numbers are matching the case.

**Comment by Sam1301** [comment]
@meghalagrawal this bug is for release v1.2.1 (https://github.com/zulip/zulip-android/releases/tag/1.2.1) hence the line numbers may have changed.

**Comment by maxymilianz** [comment]
I think I've found out, what this bug is about. In my opinion, `public boolean scrolledToLastMessage()`, which is in MessageListFragment.java (line 790) should first check, what `linearLayoutManager.findLastVisibleItemPosition()` returns and then, if it != -1, call `adapter.getItem(int position)` method with it as an argument. If it == -1, then we should change it to some default value.
So it should look somewhat like this (if we want `scrolledToLastMessage` use position 0 as default):
`public boolean scrolledToLastMessage() {
        int position = linearLayoutManager.findLastVisibleItemPosition();
        if (position != -1)
            position = 0;
        Object object = adapter.getItem(position);
        return object instanceof Message && (((Message) object).getId() >= app.getMaxMessageId() - 2);
    }`
(I'm sorry I can't make this code look normal here.)

**Comment by meghalagrawal** [comment]
This is a solution but the thing is this is not the real Culprit.

We should know in which case is it Returning -1 ?? and why ?
