### ISSUE TITLE
Crash in CustomHtmlToSpannedConverter

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#476]
This is a crash from crashlytics; it happens on app open reliably for one user against chat.zulip.org (not sure what's special about his data).

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.io.StringReader.<init>(StringReader.java:47)
       at com.zulip.android.util.CustomHtmlToSpannedConverter.convert(CustomHtmlToSpannedConverter.java:485)
       at com.zulip.android.models.Message.formatContent(Message.java:367)
       at com.zulip.android.models.Message.getFormattedContent(Message.java:553)
       at com.zulip.android.activities.RecyclerMessageAdapter.onBindViewHolder(RecyclerMessageAdapter.java:377)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1100)
       at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:804)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:818)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1191)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3178)
       at android.view.View.layout(View.java:17945)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2716)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7450)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by maxymilianz** [comment]
The following is kind of ad hoc solution, but seems to be working:
`if (mSource != null)
                mReader.parse(new InputSource(new StringReader(mSource)));
            // ELSE HANDLE ERROR`

**Comment by dehnert** [comment]
FWIW, I just hit the ~"declare bankruptcy" button in the webapp and the Android app seemed to start working again. If you're having trouble reproducing (though it sounds like maybe @maxymilianz did?), it might be worth trying to get a couple thousand unread messages.

**Comment by Sam1301** [comment]
Since `formattedContent` is never set to any value in the existing code except while updating messages in case of update events, I wonder if its possible for `content` field to be null for GET v1/messages or `rendered_content` to be null in case of update_message events? Or perhaps this has been a bug in the past? (cc @timabbott)

**Comment by timabbott** [comment]
Ahh, yes, in an `update_message` event that only changes the topic (and not the content), `rendered_content` will not be present in the `update_message` event.

**Comment by Sam1301** [comment]
oh yeah, thanks, verified 👍
