### ISSUE TITLE
Crash on First Launch

### ISSUE THREAD

**Issue by dmorrison42** [zulip/zulip-android#6]
Zulip crashes on my Nexus 7 when launching immediately after installation.

Reproduction Steps
-------------------------
0. Ensure Zulip is removed
1. Install Zulip via the Google Play store
2. Press Launch
3. Notice app does not launch

Expected Results
----------------------
Zulip login form is displayed.

Actual Results
-------------------
A white pane is briefly displayed and closes.

Work Around
-----------------
Reboot device

Device Info
--------------
Model number: Nexus 7
Android version: 5.1.1
Kernel version: 3.4.0-g8aa6344
Build number: LMY48M

**Comment by ff-** [comment]
Happens to me too. Relevant stack trace:
```
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View android.view.MenuItem.getActionView()' on a null object reference
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at com.zulip.android.ZulipActivity.onPrepareOptionsMenu(ZulipActivity.java:455)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at android.app.Activity.onPreparePanel(Activity.java:2841)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:472)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:461)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:628)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:972)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:309)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5292)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
11-02 14:12:41.352 29387-29387/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```

**Comment by earplay** [comment]
Replicated
Nexus 6
Android 5.1.1
Kernel 3.10.40-gc16a3c6

**Comment by semipermeable** [comment]
Replicatd on Nexus 5x, Android 6.0, kernel 3.10.73-g60cf314

**Comment by MetalCanine** [comment]
Replicated
Samsung Galaxy Tab E
Android 5.1.1
Kernel 3.10.49-6302417

**Comment by ywecur** [comment]
Me too
Nexus 6P
Android 6.0.1
